# Generated by Django 3.0.6 on 2020-05-22 03:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 3, 23, 1, 342204, tzinfo=utc)),
        ),
    ]
